### 0
GET {{baseUrl}}/seasons
Accept: application/json

### 1
POST {{baseUrl}}/seasons
Content-Type: application/json

[
  {
    "year": 2028,
    "alias": "S2028-2029"
  }
]

### 2
PUT {{baseUrl}}/seasons/2028/status
Content-Type: application/json

{
  "status": "STARTED"
}
