### GET SEASONS
GET {{baseUrl}}/seasons
Accept: application/json

### SEASON CREATION
POST {{baseUrl}}/seasons
Content-Type: application/json

[
  {
    "year": 2024,
    "alias": "S2024-2025"
  },
  {
    "year": 2025,
    "alias": "S2025-2026"
  }
]

### STARTING SEASON
###
PUT {{baseUrl}}/seasons/2024/status
Content-Type: application/json

{
  "status": "STARTED"
}
###
PUT {{baseUrl}}/seasons/2025/status
Content-Type: application/json

{
  "status": "STARTED"
}
