INSERT INTO country (id, name, continent) VALUES
  ('AL', 'Albania', 'EUROPE'),
  ('AD', 'Andorra', 'EUROPE'),
  ('AM', 'Armenia', 'EUROPE'),
  ('AT', 'Austria', 'EUROPE'),
  ('BY', 'Belarus', 'EUROPE'),
  ('BE', 'Belgium', 'EUROPE'),
  ('BA', 'Bosnia and Herzegovina', 'EUROPE'),
  ('BG', 'Bulgaria', 'EUROPE'),
  ('HR', 'Croatia', 'EUROPE'),
  ('CY', 'Cyprus', 'EUROPE'),
  ('CZ', 'Czech Republic', 'EUROPE'),
  ('DK', 'Denmark', 'EUROPE'),
  ('EE', 'Estonia', 'EUROPE'),
  ('FI', 'Finland', 'EUROPE'),
  ('FR', 'France', 'EUROPE'),
  ('GE', 'Georgia', 'EUROPE'),
  ('DE', 'Germany', 'EUROPE'),
  ('GR', 'Greece', 'EUROPE'),
  ('HU', 'Hungary', 'EUROPE'),
  ('IS', 'Iceland', 'EUROPE'),
  ('IE', 'Ireland', 'EUROPE'),
  ('IT', 'Italy', 'EUROPE'),
  ('KZ', 'Kazakhstan', 'EUROPE'),
  ('XK', 'Kosovo', 'EUROPE'),
  ('LV', 'Latvia', 'EUROPE'),
  ('LI', 'Liechtenstein', 'EUROPE'),
  ('LT', 'Lithuania', 'EUROPE'),
  ('LU', 'Luxembourg', 'EUROPE'),
  ('MT', 'Malta', 'EUROPE'),
  ('MD', 'Moldova', 'EUROPE'),
  ('MC', 'Monaco', 'EUROPE'),
  ('ME', 'Montenegro', 'EUROPE'),
  ('NL', 'Netherlands', 'EUROPE'),
  ('MK', 'North Macedonia', 'EUROPE'),
  ('NO', 'Norway', 'EUROPE'),
  ('PL', 'Poland', 'EUROPE'),
  ('PT', 'Portugal', 'EUROPE'),
  ('RO', 'Romania', 'EUROPE'),
  ('RU', 'Russia', 'EUROPE'),
  ('SM', 'San Marino', 'EUROPE'),
  ('RS', 'Serbia', 'EUROPE'),
  ('SK', 'Slovakia', 'EUROPE'),
  ('SI', 'Slovenia', 'EUROPE'),
  ('ES', 'Spain', 'EUROPE'),
  ('SE', 'Sweden', 'EUROPE'),
  ('CH', 'Switzerland', 'EUROPE'),
  ('TR', 'Turkey', 'EUROPE'),
  ('UA', 'Ukraine', 'EUROPE'),
  ('GB', 'United Kingdom', 'EUROPE'),
  ('VA', 'Vatican City', 'EUROPE');
